config/routes.rb
Rails.application.routes.draw do
  # これなんやっけ？
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'users/create'
  
  # トップページ
  root to: 'tasks#index'
  
  # ログイン処理用
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  # ユーザ作成用 /users/signup でアクセスできるようにする。resources に追加してnewでも可。
  get 'signup', to: 'users#new'
  
  resources :users, only: [:create]
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  # テーブル一対多
  belongs_to :user
  
  validates :content, presence: true, length: { maximum: 255 }
  validates :status, presence: true, length: { maximum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # バリデーション
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    # format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    format: { with: /\A[\w\+\-\.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    # 重複禁止: { 大文字小文字の区別なし }
                    uniqueness: { case_sensitive: false }
  
  # パスワードダイジェスト
  has_secure_password
  
  # 一対多( UserからTaskをみたとき、複数存在する  )
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Helper使う用
  include SessionsHelper
  
  # ページネーション用
  include Pagy::Backend
  
  private
  
  # アクション前のログイン確認用
  def require_user_logged_in
    unless logged_in?
      redirect_to login_path
    end
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  # 対応するModel（テーブル）がない為、受け取って引き渡すデータがない = コード不要
  # デフォルト処理として、render :new が実行され new.html.erb(view)が呼び出される。
  def new
  end
  
  # ログイン処理
  def create
    # scope を設定していたので、scopeから値を取り出す
    email = params[:session][:email].downcase
    password = params[:session][:password]
    
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  # ログアウト処理
  def destroy
    # session情報を消すことでログイン状態を維持できなくなる = ログアウト
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private
  
  # ログイン判定
  def login(email, password)
    # フォームに入力されたのと同じアドレスのユーザレコードを@userに取り出す
    @user = User.find_by(email: email)
    
    # ユーザレコードが存在する && パスワード認証が通る
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # 各アクション前にログイン確認
  before_action :require_user_logged_in
  # DRY用
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  
  def index
    # ユーザ毎に表示内容を分ける
    if logged_in?
      @task = current_user.tasks.build  # form_with 用
      #ページネーション用に追記：@pagy, ~ pagy(~)
      @pagy, @tasks = pagy(current_user.tasks.order(id: :desc))  #items: は1ページに表示するアイテム数
    end
  end
  
  def show
  end
  
  def new
    @task = Task.new
  end
  
  def create
    # ユーザ毎に処理を分ける
    # @task = Task.new(task_params)
    @task = current_user.tasks.build(task_params)
    
    if @task.save
      flash[:success] = 'Task が正常に登録されました'
      redirect_to @task
    else
      flash.now[:danger] = 'Task が投稿されませんでした'
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @task.update(task_params)
      flash[:success] = 'Task が正常に更新されました'
      redirect_to @task
    else
      flash.now[:danger] = 'Task が更新されませんでした'
      render :new
    end
  end
  
  def destroy
    @task.destroy
    
    flash[:success] = 'Task は正常に削除されました'
    redirect_to tasks_url
  end

  private
  
  # DRY：何度も書く処理は関数にしておく。
  def set_task
    @task = Task.find(params[:id])
  end
  
  #Strong parameter
  def task_params
    params.require(:task).permit(:content, :status)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  # ユーザ作成用
  def new
    @user = User.new
  end
  
  # ユーザ登録処理
  def create
    # 登録処理なので入力された値をそのまま使うのはNG。Strong Parameter使う。
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to root_url
    else
      flash[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend  #追記：ページネーション用
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def current_user
    # 簡略化：@current_user ||= User.find_by(id: session[:user_id])
    if @current_user
      return @current_user
    else
      @current_user = User.find_by(id: session[:user_id])
      return @current_user
    end
  end
  
  def logged_in?
    # 簡略化：!!current_user
    if current_user
      return true
    else
      return false
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<!-- ユーザ登録処理で失敗したときのエラーメッセージ表示用 -->
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-light bg-light">
    <div class="container-fluid ps-5">
      <a class="navbar-brand" href="/">
        <img src="/journal-check.svg" alt="" width="30" height="24" >
        Task＊List
      </a>

      <!-- ハンバーガーボタン -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- メニュー項目 -->
      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <% if logged_in? %>
          <!-- ログイン中 -->
          <div class="btn-group">
            <ul class="navbar-nav">
              <li class="nav-item"><%= link_to '新規タスクの登録', new_task_path, class: 'nav-link' %></li>
            </ul>
            <button type="button" class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><%= current_user.name %></button>
            <ul class="dropdown-menu dropdown-menu-end">
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete, class: 'nav-link' %></li>
            </ul>
          </div>
        <% else %>
          <!-- ログアウト中 -->
          <ul class="navbar-nav">
            <li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
          </ul>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasklist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!-- Optional JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  </head>

  <body data-turbolinks="false">
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="row">
  <div class="col-6">
    <%= form_with(model: task) do |f| %>
      <% if task.errors.any? %>
        <div id="error_explanation" class="alert alert-warning">
          <ul class="mb-0">
            <% task.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    
      <div class="mb-3">
        <%= f.label :status, 'ステータス' %>
        <%= f.text_field :status, class: "form-control" %>
      </div>
      
      <div class="mb-3">
        <%= f.label :content, 'タスク' %>
        <%= f.text_field :content, class: "form-control" %>
      </div>
      
      <%= f.submit '登録', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<h1>id: <%= @task.id %> のタスク編集ページ </h1>

<%= render 'form', task: @task %>

<!-- <%= link_to '一覧に戻る', tasks_path %> -->

app/views/tasks/index.html.erb
<% if logged_in? %>
  <!-- ユーザ名つきのタイトル -->
  <h1><%= current_user.name.capitalize! %>'s Tasks</h1>
  
  <!-- <ul> -->
  <!--   <% @tasks.each do |task| %> -->
  <!--   <li><%= link_to task.id, task %> : 【<%= task.status %>】 <%= task.content %></li> -->
  <!--   <% end %>   -->
  <!-- </ul> -->
  
  <div class="row">
    <div class="col-12">
      <% if @tasks.any? %>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>id</th>
              <th>ステータス</th>
              <th>タスク</th>
            </tr>
          </thead>
          <tbody>
            <% @tasks.each do |task| %>
              <tr>
                <td><%= link_to task.id, task %></td>
                <td><%= task.status %></td>
                <td><%= task.content %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <p>タスクの登録が0件です！</p>
      <% end %>
    </div>
  </div>
  <!-- ページネーション追加 -->
  <%== pagy_bootstrap_nav(@pagy) %>
  
<% else %>
  <!-- ログイン前 -->
  <div class="bg-secondary p-3 p-sm-5 my-4 rounded">
    <div class="text-center text-white">
      <h1>Welcome to the Task＊List</h1>
      <%= link_to 'Signup', signup_path, class: 'btn btn-lg btn-light' %>
      <%= link_to 'Login', login_path, class: 'btn btn-lg btn-dark' %>
    </div>
  </div>
<% end %>

app/views/tasks/new.html.erb
<h1>タスク新規作成ページ</h1>

<%= render 'form', task: @task %>

<!-- <%= link_to '一覧に戻る', tasks_path %> -->

app/views/tasks/show.html.erb
<h1>id: <%= @task.id %> のタスク詳細ページ</h1>

<!-- <p>ステータス：<%= @task.status %></p> -->
<!-- <p>タスク：<%= @task.content %></p> -->

<div class="row">
  <div class="col-12">
    <table class="table table-bordered">
      <tr>
        <th>ステータス</th>
        <td><%= @task.status %></td>
      </tr>
      <tr>
        <th>タスク</th>
        <td><%= @task.content %></td>
      </tr>
    </table>
  </div>
</div>

<%= link_to 'このタスクを編集する', edit_task_path(@task), class: "btn btn-light" %>
<%= link_to 'このタスクを削除する', @task, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: "btn btn-danger" %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up now!</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">
    
    <%= form_with(model: @user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="mb-3">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class="mb-3">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      
      <div class="mb-3">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      
      <div class="mb-3">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      
      <%= f.submit 'Sign up', class: 'btn btn-primary w-100' %>
    <% end %>
    
  </div>
</div>